version: '3'
services:
    webserver:
        build: .
        ports:
          - "8888:80"
        volumes:
          - ./:/var/www/html
        environment:
          XDEBUG_CONFIG: remote_host=host.docker.internal

